name: Contexts tuto workflow
run-name: Context workflow test | DEBUG - ${{ inputs.debug }}

on:
  workflow_dispatch:
    inputs:
      debug: 
        type: boolean
        default: false
  
env:
  NUMBER_OF_ATTEMPT: "${{github.run_attempt}}"
  MY_OVERWRITTEN_VAR: "workflow"
  
jobs:
  echo-date:
    runs-on: ubuntu-latest
    env:
      MY_OVERWRITTEN_VAR: "job"
    steps:
      - name: Display information
        run: |
          echo "something: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}, SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"

      - name: Retrieve Variable
        run: |
          echo "Variable value: ${{ vars.MY_VAR }}"
          echo "Number of attempt: ${{ env.NUMBER_OF_ATTEMPT }}"
          echo "Overwritten var: ${{ env.MY_OVERWRITTEN_VAR }}"
  
