name: First workflow  

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: running some shell echos
        run: echo "Hi $HOSTNAME"
        
      - name: checkout repository
        run: actions/checkout@v7.0.1
    
      - name: list repository files
        run: ls -aR
